// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGrmHvyPTDRaQx4_37DrkWoF0GPk_mS4',
    appId: '1:600279081068:web:aa290df4de19cfc83a7849',
    messagingSenderId: '600279081068',
    projectId: 'my-task-9254e',
    authDomain: 'my-task-9254e.firebaseapp.com',
    storageBucket: 'my-task-9254e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZf4zQX64k6MwUTwtsuFity847tI8O9s',
    appId: '1:600279081068:android:7487fe38cee4f0113a7849',
    messagingSenderId: '600279081068',
    projectId: 'my-task-9254e',
    storageBucket: 'my-task-9254e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEBbjt7WmvvdfMdF9uVvjWKHKfwPm0PiM',
    appId: '1:600279081068:ios:6427e2cdb920301c3a7849',
    messagingSenderId: '600279081068',
    projectId: 'my-task-9254e',
    storageBucket: 'my-task-9254e.appspot.com',
    iosClientId: '600279081068-1cqun7pg6rbj8csfqgq2rr5ib5nhmt79.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAmbw',
  );
}
